services:
  postgres:
    image: postgres:17.4-alpine3.21
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=training
      - PGDATA=/data/postgres
    volumes:
      - db:/data/postgres
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
networks:
  address_nw:
    name: my-custom-nw
volumes:
  db: